CREATE TABLE AIRLINE (
AirlineName VARCHAR(30) NOT NULL,
Headquarter VARCHAR(30) NOT NULL,
Region VARCHAR(30) NOT NULL,

CONSTRAINT airline_pk PRIMARY KEY (AirlineName)
);

CREATE TABLE AIRPORT (
AirportName VARCHAR(50) NOT NULL,
AirportLocation VARCHAR(30) NOT NULL,
FAAabbrv VARCHAR(30) NOT NULL,

CONSTRAINT airport_pk PRIMARY KEY (FAAabbrv)
);

CREATE TABLE PLANE(
AirlineName VARCHAR(30) NOT NULL,
TailName VARCHAR(30) NOT NULL,
Capacity INTEGER NOT NULL,
ModelNumber VARCHAR(30) NOT NULL,
PlaneName VARCHAR(30),
Manufacturer VARCHAR(30) NOT NULL,

CONSTRAINT plane_pk PRIMARY KEY (TailName),
CONSTRAINT plane_fk FOREIGN KEY (AirlineName) REFERENCES AIRLINE (AirlineName)
);

CREATE TABLE FLIGHT(
DFAAabbrev VARCHAR(30) NOT NULL,
AFAAabbrev VARCHAR(30) NOT NULL,
AirlineName VARCHAR(30) NOT NULL,
FlightNumber INTEGER NOT NULL,
DepartureTime TIME NOT NULL,
ArrivalTime TIME NOT NULL,
TailName VARCHAR(30) NOT NULL,

CONSTRAINT flight_pk PRIMARY KEY (FlightNumber),
CONSTRAINT flightArrival_fk FOREIGN KEY (AFAAabbrev) REFERENCES AIRPORT (FAAabbrv),
CONSTRAINT flightDepart_fk FOREIGN KEY (DFAAabbrev) REFERENCES AIRPORT (FAAabbrv),
CONSTRAINT flightAir_fk FOREIGN KEY (AirlineName) REFERENCES AIRLINE (AirlineName),
CONSTRAINT flightTail_fk FOREIGN KEY (TailName) REFERENCES PLANE (TailName)
);


CREATE TABLE FLIGHTCREW(
FlightCrewName VARCHAR(30) NOT NULL,

CONSTRAINT fc_pk PRIMARY KEY (FlightCrewName)
);

CREATE TABLE CREWMEMBER(
FlightCrewName VARCHAR(30) NOT NULL,
FAAID INTEGER NOT NULL,
LastName VARCHAR(30) NOT NULL,
FirstName VARCHAR(30) NOT NULL,
DOB DATE NOT NULL,

CONSTRAINT Crewm_ck UNIQUE (LastName, FirstName, DOB),
CONSTRAINT Crewm_fk FOREIGN KEY (FlightCrewName) REFERENCES FLIGHTCREW (FlightCrewName),
CONSTRAINT Crewm_pk PRIMARY KEY (FAAID)
);

CREATE TABLE PILOT(
FAAID INTEGER NOT NULL,
HoursOfExperience INTEGER NOT NULL,

CONSTRAINT pilot_fk FOREIGN KEY (FAAID) REFERENCES CREWMEMBER (FAAID),
CONSTRAINT pilot_pk PRIMARY KEY (FAAID)
);

CREATE TABLE COPILOT(
FAAID INTEGER NOT NULL,
HoursOfExperience INTEGER NOT NULL,

CONSTRAINT copilot_fk FOREIGN KEY (FAAID) REFERENCES CREWMEMBER (FAAID),
CONSTRAINT copilot_pk PRIMARY KEY (FAAID)
);

CREATE TABLE NAVIGATOR(
FAAID INTEGER NOT NULL,
Education VARCHAR(30) NOT NULL,

CONSTRAINT nav_fk FOREIGN KEY (FAAID) REFERENCES CREWMEMBER (FAAID),
CONSTRAINT nav_pk PRIMARY KEY (FAAID)
);

CREATE TABLE FlightAttendant(
FAAID INTEGER NOT NULL,
Education VARCHAR(30) NOT NULL,

CONSTRAINT fa_fk FOREIGN KEY (FAAID) REFERENCES CREWMEMBER (FAAID),
CONSTRAINT fa_pk PRIMARY KEY (FAAID)
);

CREATE TABLE FLIGHTINSTANCE(
FlightNumber INTEGER NOT NULL,
FlightDate DATE NOT NULL,
ActualDepartureTime TIME NOT NULL,
ActualArrivalTime TIME NOT NULL,
FlightCrewName VARCHAR(30) NOT NULL,

CONSTRAINT flightInst_pk PRIMARY KEY (FlightNumber,FlightDate),
CONSTRAINT flight_fk FOREIGN KEY (FlightNumber) REFERENCES FLIGHT (FLIGHTNUMBER),
CONSTRAINT flightCrew_fk FOREIGN KEY (FlightCrewName) REFERENCES FLIGHTCREW (FlightCrewName)
);

CREATE TABLE SERVICE(
ServiceType VARCHAR(30) NOT NULL,
Cost DOUBLE NOT NULL,
FlightNumber INTEGER NOT NULL,
FlightDate DATE NOT NULL,

CONSTRAINT service_pk PRIMARY KEY (ServiceType,FlightNumber,FlightDate),
CONSTRAINT service_Fk FOREIGN KEY (FlightNumber,FlightDate) REFERENCES FLIGHTINSTANCE (FlightNumber,FlightDate)

);

CREATE TABLE INCIDENTREPORT(
FlightNumber INTEGER NOT NULL,
FlightDate DATE NOT NULL,
IncidentType VARCHAR(30) NOT NULL,
Description VARCHAR(100) NOT NULL,
WriterFAAID INTEGER NOT NULL,
ReportedFAAID Integer NOT NULL,

CONSTRAINT flightToInst_pk PRIMARY KEY (FlightDate, FlightNumber,WriterFAAID,ReportedFAAID),
CONSTRAINT flightInst_fk FOREIGN KEY (FlightNumber,FlightDate) REFERENCES FLIGHTINSTANCE (FlightNumber,FlightDate),
CONSTRAINT writer_fk FOREIGN KEY (WriterFAAID) REFERENCES CREWMEMBER (FAAID),
CONSTRAINT reported_fk FOREIGN KEY (ReportedFAAID) REFERENCES CREWMEMBER (FAAID)
);
